import type { SapPurchaseRequisition } from '@sap-triage/shared';

/**
 * Realistic SAP MM Purchase Requisition mock data.
 * Field names mirror real SAP OData V4 API_PURCHASEREQ_PROCESS_SRV.
 * This data is ONLY used when SAP_MODE=sandbox.
 *
 * Covers: 3 PR types, 4 statuses, 3 account assignment categories,
 * 3 plants, 3 currencies, mix of materials and service items.
 */
export const SAP_MOCK_REQUISITIONS: SapPurchaseRequisition[] = [
  {
    PurchaseRequisition: '0010001001',
    PurchaseRequisitionType: 'NB',
    PurReqnDescription: 'IT Equipment H1 2026',
    CompanyCode: '1000',
    CreatedByUser: 'JSMITH',
    CreationDate: '2026-04-15',
    LastChangeDateTime: '2026-05-20T14:30:00Z',
    SourceDetermination: false,
    ProcessingStatus: '01',
    to_PurchaseReqnItem: [
      {
        PurchaseRequisition: '0010001001',
        PurchaseRequisitionItem: '00010',
        PurchReqnItemCategory: '0',
        AccountAssignmentCategory: 'K',
        PurchasingDocumentItemText: 'Laptop ProBook 460 G10',
        Material: 'LAPTOP-PB460',
        MaterialGroup: 'EDP',
        Plant: '1000',
        StorageLocation: '0001',
        RequestedQuantity: '5',
        RequestedQuantityUnit: 'EA',
        PriceInDocumentCurrency: '8500.00',
        DocumentCurrency: 'USD',
        DeliveryDate: '2026-06-15',
        PurchasingGroup: '010',
        PurchasingOrganization: '1000',
        RequisitionerName: 'JSMITH',
        Supplier: '0000100001',
        PurchaseRequisitionStatus: '01',
      },
      {
        PurchaseRequisition: '0010001001',
        PurchaseRequisitionItem: '00020',
        PurchReqnItemCategory: '0',
        AccountAssignmentCategory: 'K',
        PurchasingDocumentItemText: 'Wireless Mouse Logitech MX',
        Material: 'MOUSE-LGT-MX',
        MaterialGroup: 'EDP',
        Plant: '1000',
        StorageLocation: '0001',
        RequestedQuantity: '5',
        RequestedQuantityUnit: 'EA',
        PriceInDocumentCurrency: '89.99',
        DocumentCurrency: 'USD',
        DeliveryDate: '2026-06-15',
        PurchasingGroup: '010',
        PurchasingOrganization: '1000',
        RequisitionerName: 'JSMITH',
        Supplier: '0000100001',
        PurchaseRequisitionStatus: '01',
      },
    ],
  },
  {
    PurchaseRequisition: '0010001002',
    PurchaseRequisitionType: 'NB',
    PurReqnDescription: 'Raw Materials Q2 Production',
    CompanyCode: '1000',
    CreatedByUser: 'MMARTINEZ',
    CreationDate: '2026-05-01',
    LastChangeDateTime: '2026-05-22T09:15:00Z',
    SourceDetermination: true,
    ProcessingStatus: '02',
    to_PurchaseReqnItem: [
      {
        PurchaseRequisition: '0010001002',
        PurchaseRequisitionItem: '00010',
        PurchReqnItemCategory: '0',
        AccountAssignmentCategory: ' ',
        PurchasingDocumentItemText: 'Steel Sheet 2mm HR',
        Material: 'STEEL-SH-2MM',
        MaterialGroup: 'RAW',
        Plant: '2000',
        StorageLocation: '0010',
        RequestedQuantity: '500',
        RequestedQuantityUnit: 'KG',
        PriceInDocumentCurrency: '3.20',
        DocumentCurrency: 'EUR',
        DeliveryDate: '2026-06-01',
        PurchasingGroup: '020',
        PurchasingOrganization: '2000',
        RequisitionerName: 'MMARTINEZ',
        Supplier: '0000200015',
        PurchaseRequisitionStatus: '02',
      },
      {
        PurchaseRequisition: '0010001002',
        PurchaseRequisitionItem: '00020',
        PurchReqnItemCategory: '0',
        AccountAssignmentCategory: ' ',
        PurchasingDocumentItemText: 'Aluminum Profile 6060',
        Material: 'ALU-PRF-6060',
        MaterialGroup: 'RAW',
        Plant: '2000',
        StorageLocation: '0010',
        RequestedQuantity: '200',
        RequestedQuantityUnit: 'KG',
        PriceInDocumentCurrency: '5.80',
        DocumentCurrency: 'EUR',
        DeliveryDate: '2026-06-01',
        PurchasingGroup: '020',
        PurchasingOrganization: '2000',
        RequisitionerName: 'MMARTINEZ',
        Supplier: '0000200015',
        PurchaseRequisitionStatus: '02',
      },
    ],
  },
  {
    PurchaseRequisition: '0010001003',
    PurchaseRequisitionType: 'NB',
    PurReqnDescription: 'Consulting Services Q2',
    CompanyCode: '1000',
    CreatedByUser: 'ALOPEZ',
    CreationDate: '2026-05-10',
    LastChangeDateTime: '2026-05-25T16:45:00Z',
    SourceDetermination: false,
    ProcessingStatus: '01',
    to_PurchaseReqnItem: [
      {
        PurchaseRequisition: '0010001003',
        PurchaseRequisitionItem: '00010',
        PurchReqnItemCategory: '9',
        AccountAssignmentCategory: 'P',
        PurchasingDocumentItemText: 'ERP Implementation Consulting',
        Material: null,
        MaterialGroup: 'SERV',
        Plant: '1000',
        StorageLocation: null,
        RequestedQuantity: '160',
        RequestedQuantityUnit: 'HR',
        PriceInDocumentCurrency: '175.00',
        DocumentCurrency: 'USD',
        DeliveryDate: '2026-07-31',
        PurchasingGroup: '010',
        PurchasingOrganization: '1000',
        RequisitionerName: 'ALOPEZ',
        Supplier: null,
        PurchaseRequisitionStatus: '01',
      },
    ],
  },
  {
    PurchaseRequisition: '0010001004',
    PurchaseRequisitionType: 'NB',
    PurReqnDescription: 'Office Supplies May',
    CompanyCode: '3000',
    CreatedByUser: 'RGARCIA',
    CreationDate: '2026-05-15',
    LastChangeDateTime: '2026-05-26T11:00:00Z',
    SourceDetermination: false,
    ProcessingStatus: '01',
    to_PurchaseReqnItem: [
      {
        PurchaseRequisition: '0010001004',
        PurchaseRequisitionItem: '00010',
        PurchReqnItemCategory: '0',
        AccountAssignmentCategory: 'K',
        PurchasingDocumentItemText: 'A4 Paper 80g Ream',
        Material: 'PAPER-A4-80G',
        MaterialGroup: 'OFF',
        Plant: '3000',
        StorageLocation: '0001',
        RequestedQuantity: '50',
        RequestedQuantityUnit: 'EA',
        PriceInDocumentCurrency: '4.50',
        DocumentCurrency: 'MXN',
        DeliveryDate: '2026-05-30',
        PurchasingGroup: '030',
        PurchasingOrganization: '3000',
        RequisitionerName: 'RGARCIA',
        Supplier: '0000300022',
        PurchaseRequisitionStatus: '01',
      },
    ],
  },
  {
    PurchaseRequisition: '0010001005',
    PurchaseRequisitionType: 'NB',
    PurReqnDescription: 'Server Infrastructure Upgrade',
    CompanyCode: '1000',
    CreatedByUser: 'DCHEN',
    CreationDate: '2026-05-18',
    LastChangeDateTime: '2026-05-27T08:00:00Z',
    SourceDetermination: false,
    ProcessingStatus: '01',
    to_PurchaseReqnItem: [
      {
        PurchaseRequisition: '0010001005',
        PurchaseRequisitionItem: '00010',
        PurchReqnItemCategory: '0',
        AccountAssignmentCategory: 'F',
        PurchasingDocumentItemText: 'Dell PowerEdge R750xs Server',
        Material: 'SRV-DELL-R750',
        MaterialGroup: 'EDP',
        Plant: '1000',
        StorageLocation: '0002',
        RequestedQuantity: '3',
        RequestedQuantityUnit: 'EA',
        PriceInDocumentCurrency: '18500.00',
        DocumentCurrency: 'USD',
        DeliveryDate: '2026-06-05',
        PurchasingGroup: '010',
        PurchasingOrganization: '1000',
        RequisitionerName: 'DCHEN',
        Supplier: '0000100055',
        PurchaseRequisitionStatus: '01',
      },
      {
        PurchaseRequisition: '0010001005',
        PurchaseRequisitionItem: '00020',
        PurchReqnItemCategory: '0',
        AccountAssignmentCategory: 'F',
        PurchasingDocumentItemText: 'Network Switch 48-port 10G',
        Material: 'NET-SW-48-10G',
        MaterialGroup: 'EDP',
        Plant: '1000',
        StorageLocation: '0002',
        RequestedQuantity: '2',
        RequestedQuantityUnit: 'EA',
        PriceInDocumentCurrency: '4200.00',
        DocumentCurrency: 'USD',
        DeliveryDate: '2026-06-05',
        PurchasingGroup: '010',
        PurchasingOrganization: '1000',
        RequisitionerName: 'DCHEN',
        Supplier: null,
        PurchaseRequisitionStatus: '01',
      },
    ],
  },
  {
    PurchaseRequisition: '0010001006',
    PurchaseRequisitionType: 'UB',
    PurReqnDescription: 'Stock Transfer Plant 1000→2000',
    CompanyCode: '1000',
    CreatedByUser: 'SYSTEM',
    CreationDate: '2026-05-20',
    LastChangeDateTime: '2026-05-20T06:00:00Z',
    SourceDetermination: true,
    ProcessingStatus: 'N1',
    to_PurchaseReqnItem: [
      {
        PurchaseRequisition: '0010001006',
        PurchaseRequisitionItem: '00010',
        PurchReqnItemCategory: '0',
        AccountAssignmentCategory: ' ',
        PurchasingDocumentItemText: 'Finished Product FG-001',
        Material: 'FG-001',
        MaterialGroup: 'FIN',
        Plant: '2000',
        StorageLocation: '0001',
        RequestedQuantity: '100',
        RequestedQuantityUnit: 'EA',
        PriceInDocumentCurrency: '25.00',
        DocumentCurrency: 'EUR',
        DeliveryDate: '2026-05-29',
        PurchasingGroup: '020',
        PurchasingOrganization: '2000',
        RequisitionerName: 'SYSTEM',
        Supplier: null,
        PurchaseRequisitionStatus: 'N1',
      },
    ],
  },
  {
    PurchaseRequisition: '0010001007',
    PurchaseRequisitionType: 'NB',
    PurReqnDescription: 'Maintenance Spare Parts',
    CompanyCode: '2000',
    CreatedByUser: 'PNOVAK',
    CreationDate: '2026-05-05',
    LastChangeDateTime: '2026-05-15T12:30:00Z',
    SourceDetermination: false,
    ProcessingStatus: '02',
    to_PurchaseReqnItem: [
      {
        PurchaseRequisition: '0010001007',
        PurchaseRequisitionItem: '00010',
        PurchReqnItemCategory: '0',
        AccountAssignmentCategory: 'K',
        PurchasingDocumentItemText: 'Bearing SKF 6205-2RS',
        Material: 'BRG-SKF-6205',
        MaterialGroup: 'MRO',
        Plant: '2000',
        StorageLocation: '0020',
        RequestedQuantity: '20',
        RequestedQuantityUnit: 'EA',
        PriceInDocumentCurrency: '12.50',
        DocumentCurrency: 'EUR',
        DeliveryDate: '2026-05-25',
        PurchasingGroup: '020',
        PurchasingOrganization: '2000',
        RequisitionerName: 'PNOVAK',
        Supplier: '0000200099',
        PurchaseRequisitionStatus: '02',
      },
    ],
  },
  {
    PurchaseRequisition: '0010001008',
    PurchaseRequisitionType: 'NB',
    PurReqnDescription: 'Marketing Campaign Materials',
    CompanyCode: '3000',
    CreatedByUser: 'LMORALES',
    CreationDate: '2026-05-22',
    LastChangeDateTime: '2026-05-26T15:20:00Z',
    SourceDetermination: false,
    ProcessingStatus: '01',
    to_PurchaseReqnItem: [
      {
        PurchaseRequisition: '0010001008',
        PurchaseRequisitionItem: '00010',
        PurchReqnItemCategory: '9',
        AccountAssignmentCategory: 'K',
        PurchasingDocumentItemText: 'Trade Show Booth Design',
        Material: null,
        MaterialGroup: 'MKT',
        Plant: '3000',
        StorageLocation: null,
        RequestedQuantity: '1',
        RequestedQuantityUnit: 'EA',
        PriceInDocumentCurrency: '45000.00',
        DocumentCurrency: 'MXN',
        DeliveryDate: '2026-06-10',
        PurchasingGroup: '030',
        PurchasingOrganization: '3000',
        RequisitionerName: 'LMORALES',
        Supplier: null,
        PurchaseRequisitionStatus: '01',
      },
    ],
  },
  {
    PurchaseRequisition: '0010001009',
    PurchaseRequisitionType: 'NB',
    PurReqnDescription: 'Safety Equipment Annual',
    CompanyCode: '2000',
    CreatedByUser: 'HWEBER',
    CreationDate: '2026-04-01',
    LastChangeDateTime: '2026-05-01T09:00:00Z',
    SourceDetermination: false,
    ProcessingStatus: 'N5',
    to_PurchaseReqnItem: [
      {
        PurchaseRequisition: '0010001009',
        PurchaseRequisitionItem: '00010',
        PurchReqnItemCategory: '0',
        AccountAssignmentCategory: 'K',
        PurchasingDocumentItemText: 'Safety Helmet EN397',
        Material: 'SAFE-HLM-EN397',
        MaterialGroup: 'PPE',
        Plant: '2000',
        StorageLocation: '0030',
        RequestedQuantity: '50',
        RequestedQuantityUnit: 'EA',
        PriceInDocumentCurrency: '35.00',
        DocumentCurrency: 'EUR',
        DeliveryDate: '2026-04-30',
        PurchasingGroup: '020',
        PurchasingOrganization: '2000',
        RequisitionerName: 'HWEBER',
        Supplier: '0000200044',
        PurchaseRequisitionStatus: 'N5',
      },
    ],
  },
  {
    PurchaseRequisition: '0010001010',
    PurchaseRequisitionType: 'NB',
    PurReqnDescription: 'Cloud Software Licenses',
    CompanyCode: '1000',
    CreatedByUser: 'DCHEN',
    CreationDate: '2026-05-25',
    LastChangeDateTime: '2026-05-27T07:30:00Z',
    SourceDetermination: false,
    ProcessingStatus: '01',
    to_PurchaseReqnItem: [
      {
        PurchaseRequisition: '0010001010',
        PurchaseRequisitionItem: '00010',
        PurchReqnItemCategory: '9',
        AccountAssignmentCategory: 'K',
        PurchasingDocumentItemText: 'Microsoft 365 E3 Annual 50 seats',
        Material: null,
        MaterialGroup: 'SOFT',
        Plant: '1000',
        StorageLocation: null,
        RequestedQuantity: '50',
        RequestedQuantityUnit: 'EA',
        PriceInDocumentCurrency: '432.00',
        DocumentCurrency: 'USD',
        DeliveryDate: '2026-06-01',
        PurchasingGroup: '010',
        PurchasingOrganization: '1000',
        RequisitionerName: 'DCHEN',
        Supplier: '0000100010',
        PurchaseRequisitionStatus: '01',
      },
    ],
  },
];
